version: "3.9"

services:
  # This is the producer of raw data.
  illex:
    build:
      context: .
      target: illex
    command: stream -m 128 -v battery.as
    ports:
    - "10197:10197"

  # This is a standalone pulsar instance.
  pulsar:
    image: apachepulsar/pulsar:2.7.0
    command: bin/pulsar standalone
    ports:
    - "6650:6650"
    - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  # This is the consumer of the Arrow messages that are published to Pulsar by Bolson.
  consumer:
    build:
      context: .
      target: consumer
    depends_on:
      pulsar:
        condition: service_healthy

  # This is the producer of Arrow data for Pulsar
  # Bolson consumes raw data, converts it Apache Arrow data using an FPGA accelerator.
  # The Apache Arrow data is then published to Pulsar.
  bolson:
    build:
      context: .
      target: bolson
    command: stream --max-rows 8 -u pulsar://pulsar:6650 -t bolson battery.as
    depends_on:
      pulsar:
        condition: service_healthy
